begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/registers'
  require_relative 'lib/instructions'
  data = File.read('data/program')

  instructions = Instructions.parse(data)
  registers = Registers.new
  registers.instruct instructions

  puts "After completing this program, the largest value in any register is #{registers.largest_value}."
end
