begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/tower'
  data = File.read('data/tower')
  tower = Tower.parse(data)

  puts "The bottom program for this tower is called #{tower.bottom.name}."
end
