begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/pipes'
  data = File.read('data/input').chomp
  pipes = Pipes.parse(data)
  answer = pipes.group_size

  puts "There are #{answer} programs in the group containing 0."
end
