begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/firewall'

  data = File.read('data/input').chomp
  rules = {}
  data.lines.each do |line|
    depth, range = line.split(':')
    rules[depth.to_i] = range.to_i
  end
  firewall = Firewall.new(rules)
  firewall.inject
  firewall.traverse
  answer = firewall.severity

  puts "For the scanners recorded, the trip severity of a packet entering at picosecond 0 is #{answer}."
end
