begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/stream'
  data = File.read('data/input').chomp
  tokens = Stream.tokenize(data)
  score = Stream.score(tokens)
  garbage = tokens.select{|t| t.type == :garbage_content}
  garbage_length = garbage.sum{|t| t.content.length}

  puts "This input has a total score of #{score};"
  puts "the total amount of garbage is #{garbage_length} characters."
end
