begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/stream'
  data = File.read('data/input').chomp
  tokens = Stream.tokenize(data)
  score = Stream.score(tokens)

  puts "This input has a total score of #{score}."
end
