begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task :solve do
  require_relative 'lib/spiral'

  input = 312051
  vector = SpiralMemory.home_vector(input)
  distance = vector.length

  puts "Data from square #{input} must be carried #{distance} steps."
end
