begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task :solve do
  require_relative 'lib/spiral'

  input = 312051
  spiral = SpiralMemory.build_spiral_to(input)
  vector = spiral.current_square
  distance = vector.length

  puts "Data from square #{input} must be carried #{distance} steps."

  spiral = SpiralMemory.build_sum_spiral_to(input)
  value = spiral.current_value

  puts "The first value written larger than the puzzle input is #{value}."
end
