begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/tubes'
  data = File.read('data/input').chomp
  tubes = Tubes.new(data)
  letters = tubes.follow

  puts "For this diagram, the letters the packet encouters are: '#{letters}'."
end
