begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task :default => :spec
rescue LoadError
  # no rspec available
end

task 'solve' do
  require_relative 'lib/hex'
  data = File.read('data/input').chomp
  path = Hex.parse(data)
  answer = path.simplify
  furthest = path.furthest

  puts "This path leaves the child #{answer.size} steps away."
  puts "The furthest away it gets from the starting hex is #{furthest} steps away."
end
